<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17508" started-at="2019-02-18T05:47:44Z" finished-at="2019-02-18T05:48:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17508" started-at="2019-02-18T05:47:44Z" finished-at="2019-02-18T05:48:02Z">
      <class name="com.training.sanity.tests.CYT_007">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.CYT_007@47c62251]" name="setUpBeforeClass" is-config="true" duration-ms="16" started-at="2019-02-18T05:47:44Z" finished-at="2019-02-18T05:47:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.CYT_007@47c62251]" name="setUp" is-config="true" duration-ms="8496" started-at="2019-02-18T05:47:44Z" finished-at="2019-02-18T05:47:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="InvalidLoginTest()[pri:1, instance:com.training.sanity.tests.CYT_007@47c62251]" name="InvalidLoginTest" duration-ms="7070" started-at="2019-02-18T05:47:53Z" finished-at="2019-02-18T05:48:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Passwords are not Equal] but found [Passwords are not Equal
]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Passwords are not Equal] but found [Passwords are not Equal
]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.training.sanity.tests.CYT_007.InvalidLoginTest(CYT_007.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.CYT_007@47c62251]" name="tearDown" is-config="true" duration-ms="1902" started-at="2019-02-18T05:48:00Z" finished-at="2019-02-18T05:48:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.CYT_007 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
